icons_format = "{icon}"

[theme]
# theme = "ctp-mocha"
theme = "gruvbox-dark"

[icons]
icons = "material-nf"


[[block]]
block = "time"
# interval = 1
# format = " $timestamp.datetime(f:'%a %Y/%m/%d %H:%M:%S') "
interval = 5
format = " $icon $timestamp.datetime(f:'%a %Y/%m/%d %R') "

# [[block]]
# block = "music"
# format = " $icon {$combo.str(max_w:20) $play $next |}"

[[block]]
block = "net"

[[block]]
block = "temperature"
format = " $icon $max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "backlight"
device = "acpi_video"
format = " $icon $brightness "
minimum = 0

[[block]]
block = "sound"
[[block.click]]
button = "left"
action = "toggle_mute"
[[block.click]]
button = "right"
cmd = "pavucontrol"

[[block]]
block = "battery"
# full_threshold = 95
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"

# Redshift button
[[block]]
block = "custom"
command = "~/.config/i3status-rust/redshift-toggle.sh status"
interval = 1
[[block.click]]
button = "left"
cmd = "~/.config/i3status-rust/redshift-toggle.sh toggle"
[[block.click]]
button = "right"
cmd = "~/.config/i3status-rust/redshift-toggle.sh toggle"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/tomato_clock.sh"
interval = 1
[[block.click]]
button = "left"
cmd = "~/.config/i3status-rust/tomato_clock.sh left"
[[block.click]]
button = "right"
cmd = "~/.config/i3status-rust/tomato_clock.sh right"
