return {}
-- return {
--   {
--     "kevinhwang91/nvim-ufo",
--     enabled = false,
--     dependencies = { "kevinhwang91/promise-async" },
--     event = "BufRead",
--     init = function()
--       vim.o.foldcolumn = "1"
--       vim.o.foldlevel = 99
--       vim.o.foldlevelstart = 99
--       vim.o.foldenable = true
--     end,
--     keys = {
--       {
--         "zR",
--         function()
--           require("ufo").openAllFolds()
--         end,
--       },
--       {
--         "zM",
--         function()
--           require("ufo").closeAllFolds()
--         end,
--       },
--       {
--         "K",
--         function()
--           local winid = require("ufo").peekFoldedLinesUnderCursor()
--           if not winid then
--             vim.lsp.buf.hover()
--           end
--         end,
--       },
--     },
--   },
--   opts = {
--     close_fold_kinds_for_ft = {
--       default = { "imports" },
--     },
--     provider_selector = function(_, filetype)
--       return { "treesitter", "indent" }
--     end,
--   },
-- }
